name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore DependenSee.sln

      - name: Build
        run: dotnet build DependenSee.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test DependenSee.sln --configuration Release --no-build